### ISSUE TITLE
rowspan for column 1 is showing rowspan in column 2

### ISSUE THREAD

**Issue by BarunSriwastawa** [nitsugario/jQuery-Freeze-Table-Column-and-Rows#1]
[Example2.zip](https://github.com/nitsugario/jQuery-Freeze-Table-Column-and-Rows/files/760498/Example2.zip)
I tied to use jQuery-Freeze-Table-Column-and-Rows plugin facing issue when first column has rowspan=3 and second column has no row span. i tried to fix 2 columns. column 2 values override with column1. in both column displayed same values. this can be replicated with same Example2.html. only changes are make first column rowspan=3 and keep second column without any rowspan.

please refer attached zip file for html

**Comment by BarunSriwastawa** [comment]
please refer attached zip file

**Comment by nitsugario** [comment]
The problem was corrected
