### ISSUE TITLE
fht-fixed-column, fht-fixed-body height problem

### ISSUE THREAD

**Issue by flyingQuQu** [nitsugario/jQuery-Freeze-Table-Column-and-Rows#2]
Assume we have 4 rows and 4 columns.
The first row is header, and we freeze row 1 and column 1.
We set the div's height 50px in row 2 and column 4, while the other cell's height is auto.
![tim 20170413113821](https://cloud.githubusercontent.com/assets/12640805/24989475/775bc8ee-203f-11e7-81a1-707c92149519.png)

Then the height of cell in "fht-fixed-column fht-tbody" is 1px larger than the height of cell in "fht-fixed-body fht-tbody".

When the number of row is much larger, the row in "fht-fixed-column fht-tbody" and "fht-fixed-body fht-tbody" can not align in vertical, such as:
![tim 20170413113838](https://cloud.githubusercontent.com/assets/12640805/24989479/7fb2af94-203f-11e7-8e76-24657d8da4d0.png)

**Comment by nitsugario** [comment]
The problem was corrected

**Comment by udaymahadik** [comment]
how do we remove vertical scroll?
