### ISSUE TITLE
problems putting colspan in the first cell

### ISSUE THREAD

**Issue by elfanticos** [nitsugario/jQuery-Freeze-Table-Column-and-Rows#3]
when I put colspan to my first th it does not freeze well.
`<thead>
					<tr>
					    <th class="celda_encabezado_general"><p>2017</p></th>
					    <th class="celda_encabezado_general"><p>2017</p></th>
	                    <th colspan="6" class="celda_encabezado_general"><p>Area Matem&aacute;tica</p></th>
	                    <th colspan="16" class="celda_encabezado_general"><p>Area Comunicaci&oacute;n</p></th>
	                    <th rowspan="2" class="celda_encabezado_general"><p>Total</p></th>
	                    <th rowspan="2" class="celda_encabezado_general"><p>Total</p></th>
					</tr>
					<tr>
						<th class="celda_encabezado_general"><p>2017</p></th>
					    <th class="celda_encabezado_general"><p>2017</p></th>
		                <th class="celda_encabezado_general"><p>&Aacute;lgebra</p></th>
		                <th class="celda_encabezado_general"><p>Aritmetica</p></th>
		                <th class="celda_encabezado_general"><p>Geometria</p></th>
		                <th class="celda_encabezado_general"><p>R. Verbal</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>&Aacute;lgebra</p></th>
		                <th class="celda_encabezado_general"><p>Aritmetica</p></th>
		                <th class="celda_encabezado_general"><p>Geometria</p></th>
		                <th class="celda_encabezado_general"><p>R. Verbal</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
		                <th class="celda_encabezado_general"><p>Plan Lector</p></th>
              		</tr>
				</thead>`
 Thanks for your time

**Comment by udaymahadik** [comment]
how to remove vertical scroll?

**Comment by nitsugario** [comment]
@udaymahadik  Increasing the vertical size of your container.

**Comment by nitsugario** [comment]
@elfanticos  remember that to freeze COLSPAN must be even values in the header as the body.
