### ISSUE TITLE
Not able to sort or search through the column 

### ISSUE THREAD

**Issue by vinayrevanna** [nitsugario/jQuery-Freeze-Table-Column-and-Rows#5]
I have freezed first 3 columns But when I try to search through the 3rd column data and display it only if it matches the search criteria . ALL the freezed fields will be present regardless of search.
But it works basic table IF I did not call  $("#pruebatabla").CongelarFilaColumna({lboHoverTr:true}); in script.

**Comment by nitsugario** [comment]
This is due to the Ids of the cells, since the frozen columns are in another table, to access the cells add an ID to each one.
