### ISSUE TITLE
if rowspan

### ISSUE THREAD

**Issue by michbudz** [nitsugario/jQuery-Freeze-Table-Column-and-Rows#6]
Hi,
I suggest to change all if statement from
`if ( jQuery(this).attr("rowspan") )`
to
`if ( jQuery(this).attr("rowspan") > 1 )`

also 

`if ( jQuery(this).attr("colspan") )`
to
`if ( jQuery(this).attr("colspan") > 1 )`

sometimes there is a need to create rowspan = 1 or colspan = 1, then library works unpredictably.
Thanks, great work.
Michał

**Comment by nitsugario** [comment]
Thank you for your contribution Michal.
